# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Glad_config = debug
  GLFW_config = debug

else ifeq ($(config),release)
  Glad_config = release
  GLFW_config = release

else ifeq ($(config),dist)
  Glad_config = dist
  GLFW_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Glad GLFW

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Glad -f Makefile config=$(Glad_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/GLFW -f Makefile config=$(GLFW_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/GLFW -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   GLFW"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"